### ISSUE TITLE
Concerning TODO WizardModelStrategy#isLastStepEnabled() of AbstractWizard

### ISSUE THREAD

**Issue by Patrick1701** [sebfz1/wicket-jquery-ui#142] opened 2014-12-16 08:32 UTC
Hi Sebastien,
I try to disable the finish button by using ```setComplete(false)``` (static Wizard), but ```AbstractWizard#onConfigure(...)``` does not pay attention for ```IWizardModel#isLastAvailable()```.

I found a todo of yours, thinking about a ```WizardStrategy#isLastStepEnabled```, but I think you just could ask ```IWizardModel#isLastAvailable()``` and your todo might be completed?

kind regards
Patrick

**Comment by Patrick1701** [comment] 2015-03-24 13:50
Hi,
I am not sure... if I am able to reproduce this for now, and follow my own question anymore. Its from december. ;-)

If you like, close this issue... I can reopen it, in case I will need further help.

best regards
Patrick

**Comment by sebfz1** [comment] 2015-03-24 13:59
Ok, I will close it. Do not hesitate to reopen it if your question come back in mind! :)

**Comment by Patrick1701** [comment] 2015-11-24 08:42
Hi Sebastien,
ha, now, I got it. I'm able to repro it in your samples project. :)

How would you like the report? As quickstart, as pull request, just by text?

kind regards
Patrick
P.s. how do I re-open this issue? Don't have any button?

**Comment by sebfz1** [comment] 2015-11-24 08:48
Hi Patrick,

If you can repo on the sample, just explain me how and I will have a look :)

Thanks & best regards,
Sebastien

**Comment by Patrick1701** [comment] 2015-11-24 09:00
Ok, take your ```DefaultWizardPage.UserWizard``` and change ```setLastVisible(false)``` to ```true```.
Also, add ```setCancelVisible(false)```. Its the same issue for this button.

- Enter the DefaultWizardPage
- Open the 'Create User Wizard'  /  '>>' and 'cancel' are invisible.
- Close the wizard
- Reload the Page
- Open the 'Create User Wizard'  /  '>>' and 'cancel' are visible.

___

While reading our chat above I'm not sure, if this issue exactly matches.
In the headline/summary I mentioned the ```isLastStepEnabled()```-TODO, but I asked for the finish-button state enable/disable.
I remember while I was investigating, I was thinking the lastStepEnabled-feature does also takes care for finish button state in some way. But I'm not sure anymore. So, If I mix something up here... sorry.

Patrick

**Comment by Patrick1701** [comment] 2015-12-14 15:18
Hi Sebastien,
did you have a look at this issue?

best regards
Patrick

**Comment by sebfz1** [comment] 2015-12-14 15:21
Well... not yet, sorry! :/

**Comment by sebfz1** [comment] 2015-12-14 15:41
Lol, just got it! This one is funny! ;)

**Comment by Patrick1701** [comment] 2015-12-14 16:13
?!? Enlight me... :satisfied:

**Comment by sebfz1** [comment] 2015-12-14 16:37
This is an issue in `DialogButton#setVisible`

```java
public void setVisible(boolean visible, IPartialPageRequestHandler handler)
{
	if (this.visible != visible)
	{
		// the second time, we have false != false so we never get into the block...
		this.visible = visible;

		if (visible)
		{
			this.show(handler);
		}
		else
		{
			this.hide(handler);
		}
	}
```

The condition was intended to save a js statement, but I can remove it...

**Closed** 2015-12-14 16:54 UTC
Labels: not repro

**Comment by Patrick1701** [comment] 2015-12-14 17:31
Lol, too. Déjà-vu ... have a look at #147
