### ISSUE TITLE
Ellipsis near checkboxes in DataTable 

### ISSUE THREAD

**Issue by pekour** [sebfz1/wicket-jquery-ui#330] opened 2021-03-22 15:22 UTC
In Chrome there are little ellipsis near checkboxes in CheckboxColumn, sometimes disappearing when window is resized. 
Wicket Kendo UI 8.11.0
Kendo UI v2021.1.224
The following piece of CSS helped me, but probably you can find better solution.
```
td, th {
    text-overflow: clip !important;
}
```
![image](https://user-images.githubusercontent.com/16133028/112273813-71578700-8c86-11eb-81b4-1580c46dd07c.png)

**Comment by sebfz1** [comment] 2021-03-27 07:10
I could not reproduce the issue using Chromium, so it is hard to find the appropriate settings to update

![image](https://user-images.githubusercontent.com/1717144/112713008-25227600-8f16-11eb-9371-8e6a098dbf97.png)

I think you can easily make the ellipsis disappearing by using the `CheckboxColumn` ctor that takes the column `width` as argument.

```
columns.add(new CheckboxColumn(42)); // default is 40
```

I'm closing the issue, feel free to reopen if it the above does not solve it.

**Closed as completed by sebfz1** 2021-03-27 07:10 UTC
