### ISSUE TITLE
Kendo Scheduler / .refresh() after a replace (-> target.add(scheduler)) does not work

### ISSUE THREAD

**Issue by Patrick1701** [sebfz1/wicket-jquery-ui#182] opened 2015-07-15 08:48 UTC
Hi Sebastien,
concerning this issue
https://github.com/sebfz1/wicket-jquery-ui/issues/116#issuecomment-59229494

I played a bit and I found out, it is working if I apply a delay to the refresh()-method.
```
	public void refresh(AjaxRequestTarget target)
	{
		target.appendJavaScript(String.format("window.setTimeout(function(){ var widget = %s; widget.dataSource.read(); widget.refresh(); }, 10);", this.widget()));
	}
```
It seems to me wickets appendJavascript is buggy, but I'm not really sure.
Javadoc says appendJavascript code is executed at the end of the component replace.
But here it is executed before; the delay-hack can fix it.

What do you think?
Maybe your new super-powers could help here, too? :-D

best regards
Patrick

**Comment by sebfz1** [comment] 2015-07-15 09:22
Hi Patrick,

From your previous comment [1], kendo-ui's libraries are not loaded in a priority manner. Could you fix this? If it does not correct the issue please give me the exact error message...

Thanks & best regards,
Sebastien.

[1] https://github.com/sebfz1/wicket-jquery-ui/issues/155#issuecomment-121502022

**Comment by martin-g** [comment] 2015-07-15 09:26
> Javadoc says appendJavascript code is executed at the end of the component replace.
> But here it is executed before; the delay-hack can fix it.

`#appendJavaScript()` is executed **after** the component replacement.

It seems your custom appendJS is executed before Wicket jQuery UI's one. The one that makes the HTMLElement a KendoUI widget.

**Comment by Patrick1701** [comment] 2015-07-15 09:36
>It seems your custom appendJS is executed before Wicket jQuery UI's one. The one that makes the HTMLElement a KendoUI widget.

Ah, ok you mean, the wicket component replacement itself is already done and worked as expected.
Ok, but how can I ensure the kendoScheduler initialization script has an higher priority than my appendJavaScript js?

**Comment by sebfz1** [comment] 2015-07-15 09:43
I've repro it:

```javascript
Wicket.Ajax: 
Wicket.Ajax.Call.processEvaluation: Exception evaluating javascript: TypeError: grid is undefined, text: 
(function(){var grid = jQuery('#datatable7').data('kendoGrid'); grid.dataSource.read(); grid.refresh();})();
(function(){jQuery('#datatable7').kendoGrid({ "columnMenu": true, "dataSource": { "schema": { "total": "__count", "model": { "fields": {  } }, "data": "results" }, "serverFiltering": true, "transport": { "read": "./DefaultDataTablePage?2-1.IBehaviorListener.0-form-datatable" }, "serverSorting": true, "pageSize": 25, "type": "json", "serverPaging": true }, "height": 430, "sortable": true, "pageable": { pageSizes: [ 25, 50, 100 ] }, "columns": [ { "title": "ID", "field": "id", "hidden": false, "width": 50 }, { "title": "Name", "field": "name", "hidden": false }, { "title": "Description", "field": "description", "hidden": false }, { "title": "Price", "field": "price", "hidden": false, "width": 70, "format": "{0:c2}" }, { "title": "Vendor", "field": "vendor$name", "hidden": false } ], "groupable": true });})();
````

There is a difference of order/priority depending of if the statement comes from a component or a behavior. It seems the component has the priority (that's why it work with the timeout).

I already has this problem in the past (but I am pretty sure it is by design), I add to delegate to the underlying behavior...

@martin-g , any clue to workaround this?

Thanks & best regards,
Sebastien.

**Comment by martin-g** [comment] 2015-07-15 09:46
No, sorry!

Please create a quickstart and I'll take a look when I can.

**Comment by sebfz1** [comment] 2015-07-15 12:53
Hi Patrick,

> I already had this problem in the past (but I am pretty sure it is by design), I had to delegate to the underlying behavior...

My comment was not accurate, it was about `#renderHead`, not `appendJavaScript` (and it was in wicket1.5 IIRC...)

I should stop investigating for today. I've identified the execution sequence order:

```
1. com.googlecode.wicket.kendo.ui.scheduler.Scheduler.renderHead(IHeaderResponse) - response#render
2. com.googlecode.wicket.kendo.ui.scheduler.SchedulerBehavior.renderHead(Component, IHeaderResponse) - response#render
3. com.googlecode.wicket.kendo.ui.scheduler.Scheduler.refresh(IPartialPageRequestHandler) - appendJavaScript
4. com.googlecode.wicket.jquery.core.JQueryAbstractBehavior.renderHead(Component, IHeaderResponse) - appendJavaScript
```

For things to work correctly, `4.` should be executed before `3.`.
This is actually not the case because `#refresh` call is a direct statement insertion (`appendJavaScript`), while the call to `#renderHead+appendJavaScript` is delayed.

I will continue thinking about this later...

Best regards,
Sebastien.

**Comment by sebfz1** [comment] 2015-07-15 16:34
Diving in the code indicates that `OnDomReadyHeaderItem` has a special favor, and is rendered before the statements added via `appendJavaScript ` ...

Both `AjaxRequestHandler` and `WebSocketRequestHandler` uses `PartialPageUpdate` so I will give a try with `OnDomReadyHeaderItem`. But I've got a lot to test... (first test actually resolves the issue)

I will keep you in touch!

**Comment by martin-g** [comment] 2015-07-15 17:02
:+1: 
I can test with my app too.

**Comment by Patrick1701** [comment] 2015-07-16 07:06
Same for me... just give a hint...

**Comment by sebfz1** [comment] 2015-07-16 12:57
Hi Martin & Patrick,

I've created `master-ondomready` (based on wicket-7) and `wicket6-ondomready` (based on wicket-6) with the correction.

On the principle, I am not really happy to have to register to ondomready event on ajax return (should be direct statement execution IMO) , moreover statements added with `appendJavaScript` are (or should be) directly executed. So there is something in my mind that's says "this is a chance the registration and the execution occurs simultaneously, and before the direct statement"... Or maybe this is logical, in which case I missed the code/theory that proves this...

Anyway, it seems to work...

I cannot deploy `7.0.0-SNAPSHOT` & `6.20.1-SNAPSHOT` for now, but I can do it tonight if needed...

Thanks a lot for your testing time, it's a crucial point!
Also it is important to test through different browser... (I am using FF)

Best regards,
Sebastien.

**Comment by Patrick1701** [comment] 2015-07-16 13:15
Hi Sebastien,
thanx!

>  but I can do it tonight if needed...

I try to test tomorrow. Could use my fork here... so no need to deploy if it would lead into stress for you.

Patrick

**Comment by sebfz1** [comment] 2015-07-16 13:19
If you can use the fork/branch, well that's better for me...
Thanks Patrick!

**Comment by sebfz1** [comment] 2015-07-16 13:35
Patrick, I forgot to mention I've recently upgraded kendo-ui to `2015.2.624`. This may impact the rendering (except if you have a custom theme, in which case you still we be aligned and there is no need to upgrade your kendo-all.js version now...)

**Comment by Patrick1701** [comment] 2015-07-16 13:37
Ok, I will keep in mind...

**Comment by martin-g** [comment] 2015-07-17 09:01
I've tested my app with the 6.x branch and everything seems to be fine.
I don't have time to do a proper review of the change. Too much work here ... :-/

**Comment by sebfz1** [comment] 2015-07-17 10:16
:+1:

**Comment by Patrick1701** [comment] 2015-07-17 15:13
I've tested my scheduler integration with the ```wicket6-ondomready``` branch.
Looks good to me as well...

**Comment by sebfz1** [comment] 2015-07-17 15:19
Thanks Patrick!

**Comment by sebfz1** [comment] 2015-07-26 13:31
- merged `master-ondomready` to `master`
- merged `wicket6-ondomready` to `wicket6`
- deployed `7.0.0-SNAPSHOT`
- deployed `6.20.1-SNAPSHOT`

**Closed by sebfz1** 2015-07-26 13:31 UTC
Labels: bug
